### PR TITLE
Fix MIRACLReranking metric filter

### PR DESCRIPTION
**Pull request by artemsnegirev**
Fixes an issue where models loaded from metadata could not be updated. It's ruMTEB case only as it includes MIRACLReranking. Should work for all languages.

### CODE REVIEW

**Comment by artemsnegirev** [comment]
@KennethEnevoldsen could you review?

**Review by KennethEnevoldsen — APPROVED** [review]

**Comment by artemsnegirev** [comment]
@KennethEnevoldsen, @Muennighoff and could you merge this 😁

**Comment by Muennighoff** [comment]
Probably not related to this PR but it is inconsistent we are calling it `ndcg_at_1` but `NDCG@1(MIRACL)` no?

**Comment by Samoed** [comment]
Maybe this is because previously I've added `NDCG@10(MIRACL)`, because this is `main_metric` for [MiracleReranking](https://github.com/embeddings-benchmark/mteb/blob/25b7a2fd1c6c1c24a48bf3c2c4d8c00dfa2820b9/mteb/tasks/Reranking/multilingual/MIRACLReranking.py#L68). But currently main metrics for reranking task is `map` on the leaderboard, so I think that this should be changed to `MAP@1(MIRACL)`. [Example, metrics from real results](https://github.com/embeddings-benchmark/results/blob/1b85142a5025f370ea2a3cbb6680cac8d6a1ec70/results/BAAI__bge-m3/5617a9f61b028005a4858fdac845db406aefb181/MIRACLReranking.json#L9C10-L15)

**Comment by artemsnegirev** [comment]
Yes, it's a good point. MIRACL's scores are now stored as `<METRIC>@k(MIRACL)`. Example [here](https://github.com/embeddings-benchmark/results/blob/main/results/BAAI__bge-m3/5617a9f61b028005a4858fdac845db406aefb181/MIRACLReranking.json). And we faced the same [problem](https://github.com/embeddings-benchmark/leaderboard/blob/f2faa72281aaf62cdbbd0409f7445b282a2861c1/refresh.py#L170) for scores that are loaded from the repo of results.

**Comment by artemsnegirev** [comment]
@KennethEnevoldsen should we change `NDCG@10(MIRACL)` to `MAP@10(MIRACL)` in [MIRACLReranking](https://github.com/embeddings-benchmark/mteb/blob/25b7a2fd1c6c1c24a48bf3c2c4d8c00dfa2820b9/mteb/tasks/Reranking/multilingual/MIRACLReranking.py#L68) for consistency? Or it's okay to use MAP in leaderboard and leave NDCG as main score?

**Comment by Samoed** [comment]
@Muennighoff

**Comment by KennethEnevoldsen** [comment]
Sorry for the late response on this. 

>@KennethEnevoldsen should we change NDCG@10(MIRACL) to MAP@10(MIRACL) in [MIRACLReranking](https://github.com/embeddings-benchmark/mteb/blob/25b7a2fd1c6c1c24a48bf3c2c4d8c00dfa2820b9/mteb/tasks/Reranking/multilingual/MIRACLReranking.py#L68) for consistency? Or it's okay to use MAP in leaderboard and leave NDCG as main score?

I would say leave it as is. This reflect the recommended metric by the authors (as far as I recall)

**Review by KennethEnevoldsen — APPROVED** [review]

**Comment by KennethEnevoldsen** [comment]
I have merged it in following the stated main metric. 

Re. scores using MAP vs NDCG. I generally think each benchmark should be able to specify their desired metrics. This leaves the main metric as a recommendation (and default). This is something we are working toward, which is not currently in place.

**Pull request merged**
