### PR TITLE
Update COIR default.jsonl

### PR DESCRIPTION
**Pull request by archersama**
I have updated the CoIR leaderboard scores on the MTEB benchmark. Additionally, I have executed the `apps.py` script to ensure the content is displayed correctly.

### CODE REVIEW

**Comment by KennethEnevoldsen** [comment]
Hmm I am not too familiar with the leaderboard, but this seems like a manual input of the results (@Muennighoff). Shouldn't this be derived from the [results](https://github.com/embeddings-benchmark/results) repository?

**Comment by archersama** [comment]
> Hmm I am not too familiar with the leaderboard, but this seems like a manual input of the results (@Muennighoff). Shouldn't this be derived from the [results](https://github.com/embeddings-benchmark/results) repository?

I noticed that CoIR was incorrectly labeled with only two datasets, I changed the label to include all ten datasets so that it now shows the correct datasets. I additionally uploaded all the results manually. So I should upload the model  performance to the results repository?

**Comment by Samoed** [comment]
Yes. And after that you should delete `EXTERNAL_MODEL_RESULTS.json` if model presented here and run `refresh.py`

**Comment by KennethEnevoldsen** [comment]
But shouldn't it be specified in the [config](https://github.com/embeddings-benchmark/leaderboard/blob/main/config.yaml) and then be auto-updated (@orionw adding you here well since you have more experience with the leaderboard). 

Following the [instruction](https://github.com/embeddings-benchmark/mteb/blob/main/docs/adding_a_leaderboard_tab.md) for a leaderboard tab, it doesn't seem like this is the intended approach. It might be that the docs are outdated.

**Comment by orionw** [comment]
Thanks @KennethEnevoldsen! Yes this file will get over-written when the nightly CI occurs. 

It is definitely possible that some docs are outdated, sorry about that! 

> noticed that CoIR was incorrectly labeled with only two datasets, I changed the label to include all ten datasets so that it now shows the correct datasets.

@archersama this should be done in the config that Kenneth referenced, let me know if you have any troubles with it!

>  I additionally uploaded all the results manually. So I should upload the model performance to the results repository?

Yes, uploading them to the results repository would be the way to go!  Or if the results are attached to models you control on HF, you can add it to their README and don’t need to add it to the results repo

Again let me know if you run into any issues and we should probably add some docs on this.  Thanks for raising the issue!

**Comment by Samoed** [comment]
All tasks are already included in config, but I don't understand why tab only contains 2 datasets, because there are some results by https://github.com/embeddings-benchmark/results/commit/319e81d64298f3bdc5f09c8b6ff91f5015b3664c. I'll try to update leaderboard
 https://github.com/embeddings-benchmark/leaderboard/blob/fab8bb0162c236532b58a7a5c04aa5b5f9daa588/config.yaml#L509-L529

**Comment by Samoed** [comment]
Found issue with results repo https://github.com/embeddings-benchmark/results/pull/23

**Comment by archersama** [comment]
> [发现结果 repo embeddings-benchmark/results#23](https://github.com/embeddings-benchmark/results/pull/23)存在问题[](https://github.com/embeddings-benchmark/results/pull/23)

So the label error has been fixed?  When will we see new dataset labels?

**Comment by archersama** [comment]
> Found issue with results repo [embeddings-benchmark/results#23](https://github.com/embeddings-benchmark/results/pull/23)

So the label error has been fixed?  When will we see new dataset labels?

**Comment by KennethEnevoldsen** [comment]
There was an update 6 hours ago, @orionw any idea where the bug could be here?

**Comment by Samoed** [comment]
I don't think that this is bug, because results can't be updated correctly https://github.com/embeddings-benchmark/results/pull/25

**Comment by KennethEnevoldsen** [comment]
Thanks @Samoed for taking the time for this

**Comment by archersama** [comment]
> I don't think that this is bug, because results can't be updated correctly [embeddings-benchmark/results#25](https://github.com/embeddings-benchmark/results/pull/25)

The coir leaderboard error issue hasn't been fixed yet, is something wrong?

**Comment by Samoed** [comment]
PR still under review

**Comment by archersama** [comment]
> PR still under review

Thanks @Samoed for taking the time for this，I see this pr  https://github.com/embeddings-benchmark/results/pull/25 has been merged.  So CoIR leaderboard can be displayed normally？

**Comment by Samoed** [comment]
Yes, I'm working on fixing some bugs in another PR and will update the leaderboard there. It will have all results from results repo

**Comment by Muennighoff** [comment]
Maybe to prevent confusion in the future, we should add some documentation/instruction on how the results & leaderboard work and interoperate. It seems like @Samoed understands it really well - if you want to, it'd be amazing if you added some explanations to the READMEs to help others contribute more easily (https://github.com/embeddings-benchmark/leaderboard/blob/main/README.md & https://github.com/embeddings-benchmark/results/blob/main/README.md)

**Comment by archersama** [comment]
> Maybe to prevent confusion in the future, we should add some documentation/instruction on how the results & leaderboard work and interoperate. It seems like @Samoed understands it really well - if you want to, it'd be amazing if you added some explanations to the READMEs to help others contribute more easily (https://github.com/embeddings-benchmark/leaderboard/blob/main/README.md & https://github.com/embeddings-benchmark/results/blob/main/README.md)

I think so too. At the moment, it seems that some documents are outdated and cannot provide the appropriate guidance.

**Comment by yeliusf** [comment]
Hi @archersama, I saw that CoIR has been integrated into MTEB. Thanks for the awesome work! I wonder why the results on MTEB are quite different from those reported in the paper or on the leaderboard.
For example: 
- **E5-mistral-7b-instruct**
  - **Apps**: Paper: **21.33** → MTEB: **23.46**
  - **CodeFeedbackMT**: Paper: **33.65** → MTEB: **36.4**
  - **CodeFeedbackST**: Paper: **72.71** → MTEB: **76.41**
  - **CodeTransOceanContest**: Paper: **82.55** → MTEB: **88.58**
et al.

**Comment by Samoed** [comment]
I think mostly this is because mteb includes titles to the prompt, but in the paper they don't include it

**Comment by yeliusf** [comment]
Thanks, @Samoed. However, I noticed that most datasets in CoIR don't have titles. For example, in the 'apps' dataset, the title field is empty: https://huggingface.co/datasets/CoIR-Retrieval/apps-queries-corpus. Despite this, the performance improved from 21.33 in the paper to 23.46 in MTEB.

**Comment by KennethEnevoldsen** [comment]
Just adding @monikernemo here as well.

> Despite this, the performance improved from 21.33 in the paper to 23.46 in MTEB.

This seems odd. @Samoed any ideas about why this might happen?

**Comment by Samoed** [comment]
Maybe the default task prompt can affect the results, because I don't know if the prompt was used in the original paper

**Comment by monikernemo** [comment]
Besides model prompts, due to resource constraints, we could have had lowered model precision when churning the benchmarks for CoIR.

**Comment by yeliusf** [comment]
Thanks @Samoed @monikernemo for the explanation.

Could you please share the prompt that you used?

I tried my prompt and evaluate the COIR with MTEB using E5-mistral model. 
**CoIR-Text-to-Code**: "Given a text description or question, retrieve the complete code program that solves it",
**CoIR-Code-to-Text**: "Given a code snippet, retrieve the text that describes it",
**CoIR-Code-to-Code**: "Given a code snippet, retrieve relevant code to complete or enhance it",
**CoIR-Hybrid**: "Given a code snippet and a related text description or question, retrieve the relevant code or text that completes, explains, or enhances it"

**Results Comparison of E5-Mistral**:
| **Dataset**           | **APPS** | **CosQA** | **CSN-Go** | **CSN-Java** | **CSN-Javascript** | **CSN-PHP** | **CSN-Python** | **CSN-Ruby** |
|-----------------------|----------|-----------|------------|--------------|--------------------|-------------|----------------|--------------|
| **MTEB Report**   | 23.46    | 33.1      | 93.06      | 84.08        | 80.93              | 83.14       | 91.75          | 85.37        |
| **Reproduced using prompt above**   | 26.11    | 30.59     | 69.82      | 62.42        | 52.22              | 57.33       | 72.75          | 53.48        |

The main discrepancy is with CoIR CodeSearchNet, where I observe more than a 20% decrease in performance. I don't understand why this is happening. Could you please share the prompt and settings that you used?

**Comment by Samoed** [comment]
@Muennighoff added results for e5-mistral. But I think that he run just mteb with default prompt https://github.com/embeddings-benchmark/mteb/blob/main/mteb/models/instructions.py#L17. You can add these prompts to mteb

**Comment by archersama** [comment]
@Samoed Thank you for your efforts. I would like to inquire if there is a way to average the evaluation metrics of the subsets of CodeSearchNet and CodeSearchNet-CCR, and then merge them into the CodeSearchNet and CodeSearchNet-CCR datasets, similar to the [COIR leaderboard](https://archersama.github.io/coir/).

**Comment by Samoed** [comment]
There is one possible way, but it is a bit hacky and I don't know how it works with leaderboard. Currently, for [CQADupstack tasks creates special aggregation task](https://github.com/embeddings-benchmark/mteb/blob/dddf5c249bd102cd22f46965e38c1ebe0896a33d/mteb/create_meta.py#L104) when results are exported, but this not exported to results directly as far as I know. Maybe possible to make something only with leaderboard, but I'm not sure

**Comment by archersama** [comment]
> There is one possible way, but it is a bit hacky and I don't know how it works with leaderboard. Currently, for [CQADupstack tasks creates special aggregation task](https://github.com/embeddings-benchmark/mteb/blob/dddf5c249bd102cd22f46965e38c1ebe0896a33d/mteb/create_meta.py#L104) when results are exported, but this not exported to results directly as far as I know. Maybe possible to make something only with leaderboard, but I'm not sure

Perhaps we could consult with professionals, simply ensuring that they are correctly displayed on the leaderboard as results for the two datasets,@Muennighoff,@KennethEnevoldsen

**Comment by KennethEnevoldsen** [comment]
**Re scores of E5 Mistral:**

E5 mistral is run using its [implementation](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/models/e5_instruct.py) within MTEB and for the prompt they use the default prompts (as @Samoed says). So everything should be reproducible.

A good way to debug it is probably to test if the non-prompt models obtain the same performance (if that is not the case it is probably task implementation). After that, we can examine the smaller e5-large-instruct and see if the effect is due to the prompt.


> Perhaps we could consult with professionals, simply ensuring that they are correctly displayed on the leaderboard as results for the two datasets,@Muennighoff,@KennethEnevoldsen

We do have aggregation for CQADupstack, this is for backward compatibility and I would prefer not to add more datasets using the same format.

I have suggested a potential approach to solve this issue here: https://github.com/embeddings-benchmark/mteb/issues/1231

> Perhaps we could consult with professionals

@Samoed is def. a professional, but none of us have the full overview of everything that goes on in the code.

**Comment by Samoed** [comment]
I ran the COIR benchmark with `e5-base-v2` and `bge-m3` for some tasks (since others didn't fit in Kaggle's memory with batch size 8). The results for `e5-base-v2` match the benchmark, but the results for `bge-m3` are different.

[results.zip](https://github.com/user-attachments/files/17111035/results.zip)

**Comment by yeliusf** [comment]
Hi @Samoed,

Thanks for running the experiments for `e5-base-v2` and `bge-m3`. Could you also evaluate the E5-mistral model?

I tried the new prompt you mentioned [here](https://github.com/embeddings-benchmark/mteb/blob/main/mteb/models/instructions.py#L17), but the results I got are still different from the MTEB leaderboard:

| **Dataset**                          | **CSN-Go** | **CSN-Java** | **CSN-Javascript** | **CSN-PHP** | **CSN-Python** | **CSN-Ruby** |
|--------------------------------------|------------|--------------|--------------------|-------------|----------------|--------------|
| **MTEB Report**                      | 93.06      | 84.08        | 80.93              | 83.14       | 91.75          | 85.37        |
| **Reproduced using the new prompt**| 64.81      | 56.03        | 49.07              | 54.05       | 62.11          | 43.69        |

**Comment by Samoed** [comment]
[AppsRetrieval.json](https://github.com/user-attachments/files/17121108/AppsRetrieval.json)
[CodeSearchNetRetrieval.json](https://github.com/user-attachments/files/17121109/CodeSearchNetRetrieval.json)
[COIRCodeSearchNetRetrieval.json](https://github.com/user-attachments/files/17121110/COIRCodeSearchNetRetrieval.json)
@yeliusf Here my results of mistral model on go. I think that you run COIRCodeSearchNet, while in leaderboard CodeSerachRetrieval

**Comment by yeliusf** [comment]
Hi @Samoed,

I see, that makes sense. However, based on the COIR paper, they mentioned that their version of CodeSearchNet is focused on code summary retrieval, which differs from the original CodeSearchNet. Should we follow the COIR paper and rename the MTEB COIR leaderboard to COIRCodeSearchNetRetrieval rather than CodeSearchNetRetrieval and report COIRCodeSearchNetRetrieval score?

Could you also share your evaluation code? I noticed a gap between my results and your COIRCodeSearchNet score.

**Comment by archersama** [comment]
@Samoed Can you help with aggregating the subtasks of codesearchnet as well as codesearchnet-ccr into one? And use the COIR format, that should be helpful to avoid confusion for everyone!

**Comment by Samoed** [comment]
@archersama I found a way to implement this using resuls folder, but this won't work with self reported results. For more general solution of you problem you can comment in this issue I think https://github.com/embeddings-benchmark/mteb/issues/1231

**Pull request closed without merging**
